name: Deploy Static Portfolio to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'marvel-quiz-game/package-lock.json'
      
      - name: Build Marvel Quiz Game
        run: |
          cd marvel-quiz-game
          npm ci
          npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Create deployment directory
        run: |
          mkdir -p _site
          cp index.html _site/
          cp -r assets _site/ 2>/dev/null || echo "No assets directory found"
          cp -r public _site/ 2>/dev/null || echo "No public directory found"
          cp favicon.ico _site/ 2>/dev/null || cp assets/brands/favicon.png _site/favicon.ico 2>/dev/null || echo "No favicon found"
          # Copy Marvel Quiz Game
          mkdir -p _site/marvel-quiz-game
          cp -r marvel-quiz-game/dist/* _site/marvel-quiz-game/ 2>/dev/null || echo "Marvel Quiz Game not built"
          ls -la _site/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
